# Generated by Django 3.1 on 2020-09-02 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PushInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=256, verbose_name='기기값')),
                ('firebase_token', models.CharField(max_length=256, verbose_name='토큰값')),
                ('message_title', models.CharField(max_length=256, verbose_name='메시지 제목')),
                ('message_content', models.TextField(verbose_name='메시지 내용')),
                ('author', models.CharField(max_length=256, verbose_name='보낸사람')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='보낸날짜')),
            ],
        ),
    ]
