# Generated by Django 3.1 on 2020-09-02 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushinfo',
            options={'verbose_name': '푸시메시지 정보', 'verbose_name_plural': '푸시메시지 정보'},
        ),
        migrations.AlterModelTable(
            name='pushinfo',
            table='push_info',
        ),
    ]
